# netlify.toml

# Build settings
[build]
  command = "npm run build"  # Change this to your build command
  publish = "dist"           # Change this to your build output directory

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

# Asset optimization
[build.processing]
  # Example: minify JavaScript files
  js = {minify = true}
  # Add more processing settings as needed

# Functions (Netlify Functions)
[[functions]]
  directory = "netlify/functions"  # Change this to your functions directory
  # Add more function settings as needed

# Plugins
# Example: enable the Netlify Analytics plugin
[[plugins]]
  package = "@netlify/plugin-analytics"
